- src/routes/+layout.svelte
- src/routes/+page.svelte
- src/routes/account/+page.svelte
- src/routes/account/[uid]/+page.svelte
- Add Google Analytics tag
- Update system requirements on home page
- Add title to Account page
> feat(updates): website updates

- package-lock.json
- src/lib/components/AppBar.svelte
- src/lib/firebase.ts
- src/routes/account/[uid]/+page.svelte
I created some tech debt with a temporary fix for the Firebase SSR issues (just checking if it is a browser in some spots, and commenting out analytics which we aren't using). I made a card to clean that up in a more elegant solution
> feat(nav): show account button when signed in

- src/lib/firebase.ts
- src/lib/server/accountUtils.ts
- src/lib/server/firebaseAdminCredential.ts
- src/lib/server/firebaseUtils.ts
- src/lib/server/subscriptionUtils.ts
Added a new Firebase project called `blend-test` and it should now be what is connected to from all environments except for production.
> feat(dev-environment): added support for a test firebase project for lower envs

- firebase-local/rtdb.rules.json
- src/app.d.ts
- src/lib/server/firebaseUtils.ts
- src/routes/account/[uid]/+page.server.ts
- src/routes/account/[uid]/+page.svelte
- src/routes/organization/[organizationId]/+page.server.ts
- src/routes/organization/[organizationId]/InviteModal.svelte
- src/routes/organization/[organizationId]/invites/+server.ts
- src/routes/organization/[organizationId]/members/+server.ts
Also updated the rules in local and QA, need to do so in prod before deploying
> feat(god-mode): Illuminati members have full access to all organizations

- src/app.d.ts
- src/lib/components/BlogPost.svelte
- src/lib/data/blogs/align-teaching-with-the-science-of-reading/index.ts
- src/lib/data/blogs/blendable-sounds-tutorial/index.ts
- src/lib/data/blogs/what-is-a-blending-board/index.ts
- src/routes/blog/+page.svelte
- src/routes/features/+page.svelte
- src/routes/library/+page.svelte
> feat(blog): added bylines

- src/routes/api/decks/shared/+server.ts
There was a bug in deck share - we weren't checking for organization membership for the source or target user when checking if deck sharing was enabled.
> fix(deck-share): enable deck share for org members

- src/lib/server/emailUtils.ts
- src/routes/api/playlists/shared/+server.ts
- src/routes/api/playlists/shared/[sharedPlaylistId]/+server.ts
- src/routes/playlistShare/[sharedKey]/+page.server.ts
- src/routes/playlistShare/[sharedKey]/+page.svelte
- src/routes/playlistShare/accepted/+page.svelte
- src/routes/playlistShare/declined/+page.svelte
feat(share-playlists): create API endpoint /playlists/shared
feat(get-delete): implement get and delete shared playlist
feat(playlist-share): added pages for accepting or declining a shared playlist
> feat(share-playlists): API changes for sharing playlists

- src/routes/api/maintenance/copyPreloadedDecks/+server.ts
endpoint to copy preloaded decks for users who have playlists linked to them
> feat(maintenance-preloaded-decks): for updating the DB when we change the preloaded decks

- .devcontainer/devcontainer.json
- .gitignore
- firebase-local/mockData/database_export/csma-blend-default-rtdb.json
- package-lock.json
- package.json
- src/index.test.ts
- src/lib/components/AppBar.svelte
- src/lib/server/firebaseUtils.ts
- src/lib/server/subscriptionUtils.ts
- src/routes/+page.svelte
- src/routes/about/+page.svelte
- src/routes/account/+page.server.ts
- src/routes/api/flags/+server.ts
- src/routes/api/playlists/user/[playlistId]/+server.ts
- src/routes/api/user/+server.ts
- src/routes/api/user/server.test.ts
- src/routes/blendPro/success/+page.svelte
- src/routes/login/customToken/+server.ts
- src/routes/newsletter/+page.svelte
- tests/vitest-setup.ts
- vite.config.ts
To run unit tests run `npm run test:unit`
> feat(tests): added tests and various version bumps

- README.md
- firebase-local/mockData/auth_export/accounts.json
- src/lib/server/firebaseUtils.ts
- src/routes/admin/+page.svelte
- src/routes/api/admin/emulationToken/+server.ts
- src/routes/organization/[organizationId]/+page.server.ts
- src/routes/organization/[organizationId]/invites/+server.ts
Just go to admin screen, enter a UID to emulate, and hit "Start"
Note I added a new environment variable:
`PUBLIC_APP_URL="http://localhost:8060/tmp_js_export.html"`
^(local)
> feat(emulation): added user emulation to admin screen

- src/routes/focus-group-rsvp/+page.svelte
- src/routes/focus-group-rsvp/+page.ts
- src/routes/focus-group-rsvp/thank-you/+page.svelte
- src/routes/focus-group-rsvp/thank-you/+page.ts
It's quick and dirty, feel free to suggest beautification changes
https://deploy-preview-101--stellar-flan-29b1d1.netlify.app/focus-group-rsvp?name=test&email=test@test.com
> feat(focus-groups): added RSVP form

- src/lib/server/firebaseUtils.ts
- src/routes/admin/+page.server.ts
- src/routes/admin/+page.svelte
Like most of the admin functions, error handling is lacking, but this is a quick and dirty search feature that pulls up all the usual data we want about a user.
> feat(admin): quick search for user details

- src/lib/server/firebaseUtils.ts
- src/routes/admin/+page.svelte
- src/routes/api/admin/userData/+server.ts
> feat(user-data): added ability to download all user data

- src/lib/server/subscriptionUtils.ts
- src/routes/account/+page.server.ts
- src/routes/account/+page.svelte
Example:
http://localhost:5173/account?action=upgrade&promoCode=REED23
> feat(checkout): support promo codes in upgrade URL

- src/hooks.server.ts
- src/routes/api/decks/[deckId]/+server.ts
- src/routes/api/decks/preloaded/+server.ts
- src/routes/api/decks/shared/+server.ts
- src/routes/api/decks/shared/[sharedDeckId]/+server.ts
- src/routes/api/decks/user/+server.ts
- src/routes/api/decks/user/[deckId]/+server.ts
- src/routes/api/flags/+server.ts
- src/routes/api/flags/[flagName]/+server.ts
- src/routes/api/playlists/preloaded/+server.ts
- src/routes/api/playlists/shared/+server.ts
- src/routes/api/playlists/shared/[sharedPlaylistId]/+server.ts
- src/routes/api/playlists/user/+server.ts
- src/routes/api/playlists/user/[playlistId]/+server.ts
- src/routes/api/user/+server.ts
- src/routes/api/user/server.test.ts
- src/routes/login/customToken/+server.ts
This should fix the issue where we do not see the body of an error response in the app
> fix(cors): add CORS header to all server requests

- src/lib/server/subscriptionUtils.ts
- src/routes/account/+page.server.ts
- src/routes/api/admin/userData/+server.ts
- src/routes/api/decks/shared/+server.ts
- src/routes/api/playlists/shared/+server.ts
- src/routes/api/user/+server.ts
- src/routes/api/user/server.test.ts
- tests/vitest-setup.ts
Utilizing firebase for the pro flag instead of Stripe to make that retrieval much faster, and parallelized everything I could
> refactor(user-api): greatly improved performance

- package.json
- src/lib/components/Footer.svelte
- src/routes/help/feedback/+page.svelte
- src/routes/help/report-an-issue/+page.svelte
- src/routes/library/decks/[marketplaceDeckId]/+page.svelte
- src/routes/library/playlists/[playlistSlug]/+page.svelte
- src/routes/organization/+page.svelte
- src/routes/pricing/+page.svelte
Also added `npm run check` to pre-commit hook
> fix(images): fix library images and footer

- src/routes/+layout.svelte
- src/routes/+page.svelte
https://github.com/user-attachments/assets/cb770c66-af38-49f2-87f4-842796cc4d25
> feat(transitions): added page loading animation

- src/app.d.ts
- src/lib/components/AuthCheck.svelte
- src/lib/server/firebaseUtils.ts
- src/routes/login/+page.svelte
- src/routes/organization/[organizationId]/+page.server.ts
- src/routes/organization/[organizationId]/+page.svelte
- src/routes/organization/[organizationId]/members/+server.ts
- src/routes/organization/join/[organizationId]/+page.server.ts
- src/routes/organization/join/[organizationId]/+page.svelte
- src/styles/base.css
No email functionality yet, but it works end to end.
You can just go to `/organization/join/<orgId>` to request access. Maybe we can add some friendly links later but I wanted to keep it minimal for now.
> feat(organizations): added the ability to request access to an org

- firebase-local/firebase.json
- firebase-local/storage.rules
- package-lock.json
- package.json
- src/app.d.ts
- src/lib/server/firebaseAdminCredential.ts
- src/lib/server/firebaseUtils.ts
- src/routes/api/user/+server.ts
- src/routes/api/user/server.test.ts
- src/routes/organization/[organizationId]/+page.server.ts
- src/routes/organization/[organizationId]/+page.svelte
- tests/vitest-setup.ts
App PR incoming as well
Had to add firebase storage to the local emulator, which requires the following environment variable:
`FIREBASE_STORAGE_EMULATOR_HOST="127.0.0.1:9199"`
https://github.com/user-attachments/assets/523d0f2b-3be8-4f99-84db-e95034383edb
> feat(organizations): ability to upload an org logo

- src/app.d.ts
- src/lib/firebase.ts
- src/routes/admin/+page.svelte
- src/routes/admin/OrganizationEditModal.svelte
- src/routes/organization/[organizationId]/+page.svelte
> feat(admin): added more organization edit abilities to admin panel

- src/routes/organization/[organizationId]/+page.svelte
> feat(request-org-link): added more metadeta to org dashboard and added invite link for admins to copy

- src/lib/components/AppBar.svelte
- src/lib/server/subscriptionUtils.ts
- src/routes/account/plan/+page.svelte
- src/routes/pricing/+page.svelte
Already made the new prices in Stripe and updated the environment variables in Netlify
> feat(pricing): updated to new price

- .devcontainer/devcontainer.json
- firebase-local/rtdb.rules.json
- package.json
- src/app.d.ts
- src/lib/components/AppBar.svelte
- src/lib/components/ProBadgeWrapper.svelte
- src/lib/server/firebaseUtils.ts
- src/lib/server/subscriptionUtils.ts
- src/lib/utils.ts
- src/routes/account/+page.server.ts
- src/routes/admin/+layout.svelte
- src/routes/admin/+page.svelte
- src/routes/admin/organizations/+page.svelte
- src/routes/admin/partners/+page.server.ts
- src/routes/admin/partners/+page.svelte
- src/routes/admin/partners/AddRedemptionModal.svelte
- src/routes/admin/partners/PartnerEditModal.svelte
- src/routes/admin/partners/partnerCard.svelte
- src/routes/api/admin/partners/[partnerId]/logo/+server.ts
- src/routes/api/admin/partners/subscriptionData/[subscriptionId]/+server.ts
- src/routes/library/decks/upgrade/+page.svelte
- src/routes/organization/[organizationId]/+page.server.ts
- src/routes/organization/[organizationId]/+page.svelte
- src/routes/organization/invite/[inviteId]/+page.svelte
- src/routes/partners/[partnerId]/+page.server.ts
- src/routes/partners/[partnerId]/+page.svelte
- src/routes/partners/[partnerId]/+page.ts
Okay so there is too much to screenshot but you can try it yourself on the deploy preview. I created one partner in Stripe and the test environment called "Cool Reading", which you can edit by going to '/admin/partners'.
The public page for that partner would be: https://deploy-preview-161--stellar-flan-29b1d1.netlify.app/partners/-OBlW2ux06fpAPqdWVeT
^Note that I made it so that existing pro users get redirected to home when they try to access a partner page, so you need to make a new account or sign out
> feat(partners): added partner pages

- package-lock.json
- package.json
- src/lib/components/AppBar.svelte
- src/lib/components/Collapsible.svelte
- src/routes/+page.svelte
- src/routes/help/+page.ts
- src/routes/library/+page.svelte
- src/routes/library/+page.ts
- src/routes/organization/+page.svelte
- src/routes/pricing/+page.ts
Made a ton of small improvements, and added ssr and prerendering where possible. I only focused on the main pages for now, the ones that are navigable from the top bar
> fix(cls): improved layout shift on main pages

- src/lib/server/subscriptionUtils.ts
We will now rely on the new price code
> refactor(checkout): no longer adds promo code for annual subs

- src/lib/components/AppBar.svelte
> feat(shop-link): added shop link to nav bar

- src/routes/deckShare/accepted/+page.svelte
- src/routes/deckShare/declined/+page.svelte
- src/routes/organization/[organizationId]/+page.svelte
- src/routes/organization/[organizationId]/OrganizationItemTable.svelte
- src/styles/base.css
And two tiny style changes where the headings were too close to the top
> refactor(organization): change how seats are displayed for teams

- src/routes/organization/[organizationId]/+page.svelte
- src/routes/organization/[organizationId]/InviteModal.svelte
**Added alert for seat limit reached**
Chrome - 
Safari - 
**Also disabled Submit on Invite Modal if at seat limit**
> fix(seat-limit-invite-request): added check for invite requests on seat limit

- package-lock.json
- package.json
- src/routes/account/auth-switch/+page.server.ts
- src/routes/account/auth-switch/+page.svelte
https://github.com/user-attachments/assets/a7b0cf06-690f-48dc-9f83-ba514946d4d6
> feat(auth): added hidden page to downgrade to email provider
